"""Membuat tabel project_image

Revision ID: 79182fa845db
Revises: c34a2a369aef
Create Date: 2026-05-01 14:31:30.289297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79182fa845db'
down_revision = 'c34a2a369aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_image')
    # ### end Alembic commands ###
